apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.service.expose: "true"
    kompose.service.type: nodePort
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: flask-app
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: flask-app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.service.expose: "true"
        kompose.service.type: nodePort
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: flask-app
    spec:
      containers:
        - image: frgentile/flask-app:latest
          name: flask-app
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
