DEVICE_NAME = "ESP32"

WIFI_SSID = "MovistarFibra-21C690"
WIFI_PASSWORD = "_M@rgarita2024!"

BROKER_ADDRESS = "192.168.1.2"
BROKER_PORT = 1883
BROKER_USER = "your_username"
BROKER_PASSWORD = "your_password"
CLIENT_ID = "esp32_client"
DATA_TOPIC = "/data"
COMMANDS_TOPIC = "/commands"

SENSOR_SENDING_INTERVAL_MS = 5000
SENSOR_READING_INTERVAL_MS = 1000
SENSOR_TYPE = "DHT11"
SENSOR_PIN = 4
SENSOR_NAME = "dht11_sensor"
